import type {
  RideDiscipline,
  RideProfile,
} from "./types";

export const RideProfiles: Record<
  RideDiscipline,
  RideProfile
> = {
  road: {
    discipline: "road",
    displayName: "Ruta",
    idealTemperatureMin: 14,
    idealTemperatureMax: 24,
    maxWind: 20,
    maxPrecipitationProbability: 20,
    maxHumidity: 80,
    maxUvIndex: 8,
    windPenalty: 18,
    rainPenalty: 25,
    temperaturePenalty: 12,
    humidityPenalty: 6,
    uvPenalty: 6,
  },

  xc: {
    discipline: "xc",
    displayName: "Cross Country",
    idealTemperatureMin: 12,
    idealTemperatureMax: 24,
    maxWind: 25,
    maxPrecipitationProbability: 35,
    maxHumidity: 90,
    maxUvIndex: 8,
    windPenalty: 12,
    rainPenalty: 18,
    temperaturePenalty: 12,
    humidityPenalty: 4,
    uvPenalty: 5,
  },

  trail: {
    discipline: "trail",
    displayName: "Trail",
    idealTemperatureMin: 10,
    idealTemperatureMax: 25,
    maxWind: 30,
    maxPrecipitationProbability: 40,
    maxHumidity: 95,
    maxUvIndex: 9,
    windPenalty: 10,
    rainPenalty: 15,
    temperaturePenalty: 10,
    humidityPenalty: 2,
    uvPenalty: 4,
  },

  enduro: {
    discipline: "enduro",
    displayName: "Enduro",
    idealTemperatureMin: 10,
    idealTemperatureMax: 25,
    maxWind: 30,
    maxPrecipitationProbability: 50,
    maxHumidity: 100,
    maxUvIndex: 9,
    windPenalty: 8,
    rainPenalty: 12,
    temperaturePenalty: 10,
    humidityPenalty: 1,
    uvPenalty: 3,
  },

  gravel: {
    discipline: "gravel",
    displayName: "Gravel",
    idealTemperatureMin: 12,
    idealTemperatureMax: 24,
    maxWind: 25,
    maxPrecipitationProbability: 30,
    maxHumidity: 85,
    maxUvIndex: 8,
    windPenalty: 12,
    rainPenalty: 18,
    temperaturePenalty: 10,
    humidityPenalty: 4,
    uvPenalty: 5,
  },

  urban: {
    discipline: "urban",
    displayName: "Urbano",
    idealTemperatureMin: 8,
    idealTemperatureMax: 30,
    maxWind: 35,
    maxPrecipitationProbability: 60,
    maxHumidity: 100,
    maxUvIndex: 10,
    windPenalty: 6,
    rainPenalty: 8,
    temperaturePenalty: 5,
    humidityPenalty: 0,
    uvPenalty: 2,
  },
};